summarizer-web/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("videos.urls")),
    path("admin/", admin.site.urls),
]

summarizer-web/videos/urls.py
from django.urls import path 

from . import views 

urlpatterns = [
    path("", views.IndexView.as_view(), name="Index"),
    path("videos", views.VideoTableView.as_view(), name="Video Table"),
    path("videolar", views.VideoTabloView.as_view(), name="Video_Tablosu"),
    path("videos/<int:pk>/", views.DetailView.as_view(), name="detail"),
    path('add_video', views.add_video, name='add_video'),
    path('delete/<int:video_id>/', views.delete_video, name='delete_video'),
    path('get_item_details/<int:item_id>/', views.get_item_details, name='get_item_details'),
    path('get_item_details_for_delete/<int:item_id>/', views.get_item_details_for_delete, name='get_item_details_for_delete'),
]

summarizer-web/videos/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin
from pgvector.django import VectorField

class Video(models.Model):
    url = models.CharField()
    title = models.CharField(null=True)
    ext = models.CharField(null=True)
    title_with_ext = models.CharField(null=True)
    description = models.CharField(null=True)
    channel_name = models.CharField(null=True)
    channel_url = models.CharField(null=True)
    upload_date_youtube = models.DateTimeField("Date published on YouTube", null=True)
    duration = models.IntegerField(null=True)
    view_count = models.IntegerField(null=True)
    like_count = models.IntegerField(null=True)
    categories = models.CharField(null=True)
    tags = models.CharField(null=True)

    audio_path = models.CharField(null=True)
    subtitles = models.CharField(null=True)
    transcript = models.CharField(null=True)
    transcript_path = models.CharField(null=True)
    transcript_from = models.CharField(null=True)
    transcript_word_count = models.IntegerField(null=True)
    transcript_token_count = models.IntegerField(null=True)
    transcript_character_count = models.IntegerField(null=True)
    transcript_chunks = models.CharField(null=True)
    transcript_embedding = VectorField(dimensions=1536, null=True)

    date_uploaded = models.DateTimeField(null=True)
    download_start_datetime = models.DateTimeField(null=True)
    download_end_datetime = models.DateTimeField(null=True)
    download_time = models.IntegerField(null=True)
    transcribing_start_date = models.DateTimeField(null=True)
    transcribing_end_date = models.DateTimeField(null=True)
    transcribing_time = models.IntegerField(null=True)
    created_at = models.DateTimeField(editable=False, default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    is_summarized = models.BooleanField(default=False)
    is_transcribed = models.BooleanField(default=False)
    status = models.CharField(default="Pending")

    playlist_id = models.CharField(null=True)
    playlist_order = models.IntegerField(null=True)
    is_in_playlist = models.BooleanField(null=True)

    def __str__(self):
        return self.url
        
class Summary(models.Model): 
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    title = models.CharField(null=True)
    summary_text = models.CharField(null=True)
    gpt_information = models.CharField(null=True)
    gpt_model_name = models.CharField(null=True)
    gpt_input_token_count = models.IntegerField(null=True)
    gpt_output_token_count = models.IntegerField(null=True) 

    summary_path = models.CharField(null=True)
    summary_start_date = models.DateTimeField(null=True)
    summary_end_date = models.DateTimeField(null=True)
    summary_time = models.IntegerField(null=True)
    summary_token_count = models.IntegerField(null=True)
    summary_word_count = models.IntegerField(null=True)
    summary_char_count = models.IntegerField(null=True)

    created_at = models.DateTimeField(editable=False, default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "Summary of" + self.title  

summarizer-web/videos/forms.py
from django import forms
from django.forms import ModelForm
from videos.models import Video

class NameForm(forms.Form):
    your_name = forms.CharField(label="Your name", max_length=100)

class VideoForm(ModelForm):
    class Meta: 
        model = Video
        fields = ['url']

        widgets = {
            'url': forms.TextInput(attrs={'class': 'form-control'})
        }

summarizer-web/videos/views.py
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.views import generic
from videos.models import Video
from videos.serializers import VideoSerializer
from django.utils import timezone
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from django.http import JsonResponse
import requests
from django.http import HttpResponseRedirect
from django.shortcuts import render
from videos.forms import NameForm, VideoForm
import json

def get_item_details(request, item_id):
    video = get_object_or_404(Video, id=item_id)
    #print(video)
    print(request)
    return render(request, 'videos/modal.html', {'video': video})

def get_item_details_for_delete(request, item_id):
    video = get_object_or_404(Video, id=item_id)
    return render(request, 'videos/modal_warning.html', {'video': video})

def add_video(request):
    submitted = False 
    if request.method == "POST":
        form = VideoForm(request.POST)
        if form.is_valid():
            form.save()
            # TODO: Control if the input from user is a YouTube Video URL or not. 
            create_record_and_notify(request)  
            return HttpResponseRedirect('add_video?submitted=True')
    else:
        form = VideoForm
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'videos/add_video.html', {'form': form, 'submitted':submitted })

class IndexView(generic.ListView):
    template_name = "videos/index.html"
    context_object_name = "latest_video_list"

    def get_queryset(self):
        """    
        Return the last five created videos. 
        """
        #return Video.objects.filter().order_by("-created_at")[:5]
        return Video.objects.filter(status="Pending")
    
class VideoTableView(generic.ListView):
    template_name = "videos/list.html"
    context_object_name = "video_list"

    def get_queryset(self):
        """    
        Return all the videos in the database.
        """
        return Video.objects.all()
    
class VideoTabloView(generic.ListView):
    template_name = "videos/liste.html"
    context_object_name = "video_list"

    def get_queryset(self) -> QuerySet[Video]:
        return Video.objects.all()
    
class DetailView(generic.DetailView):
    model = Video
    template_name = "videos/detail.html"

    def get_queryset(self):
        return Video.objects.all()

def delete_video(request, video_id):
    video = get_object_or_404(Video, id=video_id)
    if request.method == "POST":
        video.delete()
        return redirect('Video_Tablosu')  
    return render(request, 'videos/confirm_delete.html', {'video': video})

@api_view()
def view_dtl(request):
    return Response({'success': 409, 'message': 'api'})

@api_view(['POST'])
def create_record_and_notify(request):
    url = request.POST.get('url')
    print(url)

    python_app_url = "http://127.0.0.1:5000/notify_new_data"
    payload = {
        "url": url
    }

    try:
        response = requests.post(python_app_url, json=payload)
        response.raise_for_status()  
        return JsonResponse({"message": "Record created and Python app notified."}, status=201)
    except requests.exceptions.RequestException as e:
        return JsonResponse({"error": f"Failed to notify Python app: {str(e)}"}, status=500)

@api_view(['POST'])
def notify_app(request):
    python_app_url = "http://127.0.0.1:5000/notify_new_data"
    try:
        response = requests.post(python_app_url)
        response.raise_for_status()  
        return JsonResponse({"message": "Record created and Python app notified."}, status=201)
    except requests.exceptions.RequestException as e:
        return JsonResponse({"error": f"Failed to notify Python app: {str(e)}"}, status=500)

summarizer-web/videos/templates/videos/add_video.html
{% extends "videos/base.html" %}

{% load static %}

{% block content %}
    <h1>Add Video To Database</h1>
    <br/>
    {% if submitted %}
    Your Video was submitted successfully!
    
    {% else %}

    <form action="" method=POST>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit" class="btn btn-secondary">
    </form>
{% endif %}

{% endblock %}

summarizer-web/videos/templates/videos/base.html
<!DOCTYPE html>
<html lang="en" {% block htmlAttr %}{% endblock %}>
<head>
	<meta charset="utf-8">
	<title> Summarizer | {% block title %}{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="">
	<meta name="author" content="">
	
	<!-- ================== BEGIN core-css ================== -->
	{% load static %}
	<link href="{% static '/css/vendor.min.css' %}" rel="stylesheet" />
	<link href="{% static 'css/default/app.min.css' %}" rel="stylesheet" />
	<!-- ================== END core-css ================== -->
	
	{% block css %}{% endblock %}
</head>
<body class="{{ bodyClass }}{% if appHeaderHide is not None %} pace-top {% endif %}{% if appBoxedLayout %} boxed-layout {% endif %}" {{ bodyAttr }}>
	
	<div id="app" class="app 
		{% if not appHeaderHide %}app-header-fixed{% endif %}
		{% if not appSidebarHide %}app-sidebar-fixed{% endif %}
		{% if appHeaderHide is not None %}app-without-header{% endif %}
		{% if appSidebarEnd is not None %}app-with-end-sidebar{% endif %}
		{% if appSidebarEndToggled is not None %}app-sidebar-end-toggled{% endif %}
		{% if appSidebarMinified is not None %}app-sidebar-minified{% endif %}
		{% if appSidebarWide is not None %}app-with-wide-sidebar{% endif %}
		{% if appSidebarTwo is not None %}app-with-two-sidebar{% endif %}
		{% if appSidebarHide is not None %}app-without-sidebar{% endif %}
		{% if appSidebarHover is not None %}app-with-hover-sidebar{% endif %}
		{% if appTopMenu is not None %}app-with-top-menu{% endif %}
		{% if appContentFullHeight is not None %}app-content-full-height{% endif %}
	">
		{% if appHeaderHide is None %}
			{% include 'videos/partial/header.html' %}
		{% endif %}
		
		{% if appSidebarHide is None %}
			{% include 'videos/partial/sidebar.html' %}
		{% endif %}
				
		{% if appTopMenu %}
			{% include 'videos/partial/top-menu.html' %}
		{% endif %}
		
		<div class="app-content {{ appContentClass }}">
			{% block content %}{% endblock %}
		</div>
		
	</div>

	{% include 'videos/partial/scroll-top-btn.html' %} 
	
	{% block outter_content %}{% endblock %}

	<!-- ================== BEGIN core-js ================== -->
	<script src="{% static 'js/vendor.min.js' %}"></script>
	<script src="{% static 'js/app.min.js' %}"></script>
	<!-- ================== END core-js ================== -->
	
	{% block js %}{% endblock %}
</body>
</html>

summarizer-web/videos/templates/videos/confirm_delete.html
{% extends 'videos/base.html' %}

{% load static %}

{% block content %}
<h2>Are you sure you want to delete "{{ video.title }}"?</h2>
<form method="post">
  {% csrf_token %}
  <button type="submit">Yes, delete</button>
  <a href="{% url 'Video_Tablosu' %}">Cancel</a>
</form>
{% endblock %}

summarizer-web/videos/templates/videos/detail.html
{% extends 'videos/base.html' %}
{% load markdownify %}
{% load static %}

{% block title %} {{video.title}} {% endblock %}

{% block content %}
	<!-- BEGIN breadcrumb -->
	<ol class="breadcrumb float-xl-end">
		<li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
		<li class="breadcrumb-item"><a href="javascript:;">Videos</a></li>
		<li class="breadcrumb-item active">{{video.id}}</li>
	</ol>
	<!-- END breadcrumb -->
	<!-- BEGIN page-header -->
	<h1 class="page-header">{{video.title}} <small>{{video.url}}</small></h1>
	<!-- END page-header -->
	
	<!-- BEGIN row -->
	<div class="row">
		<!-- BEGIN col-3 -->
		 		<!-- BEGIN col-3 -->
		<div class="col-xl-3">
			<div class="mb-3 fw-bold fs-13px">
				<div class="d-flex align-items-center mb-3">
					<i class="fa fa-laptop fa-lg fa-fw me-10px text-gray-600"></i>
					<div>{{ video.channel_name }}</div>
				</div>
				<div class="d-flex align-items-center mb-3">
					<i class="fa fa-clock fa-lg fa-fw me-10px text-gray-600"></i>
					<div>{{ video.upload_date_youtube }}</div>
				</div>
				<div class="d-flex align-items-center mb-3">
					<i class="fa fa-clock fa-lg fa-fw me-10px text-gray-600"></i>
					<div>{{ video.duration }}</div>
				</div>
				<div class="d-flex align-items-center mb-3">
					<i class="fa fa-heart fa-lg fa-fw me-10px text-gray-600"></i>
					<div>{{ video.like_count }}</div>
				</div>
				<div class="d-flex align-items-center mb-3">
					<i class="fa fa-eye fa-lg fa-fw me-10px text-gray-600"></i>
					<div>{{ video.view_count }}</div>
				</div>
				<div class="d-flex align-items-center mb-3">
					<i class="fa fa-tag fa-lg fa-fw me-10px text-gray-600"></i>
					<div>{{ video.categories }}</div>
				</div>
			</div>
		</div>
		<!-- END col-3 -->

		<!-- END col-3 -->
		<!-- BEGIN col-9 -->
		<div class="col-xl-9">
			<!-- BEGIN panel -->
			<div class="panel panel-inverse panel-with-tabs" data-sortable="false">
				<!-- BEGIN panel-heading -->
				<div class="panel-heading p-0">
					<!-- BEGIN nav-tabs -->
					<div class="tab-overflow">
						<ul class="nav nav-tabs nav-tabs-inverse">
							<li class="nav-item prev-button"><a href="javascript:;" data-click="prev-tab" class="nav-link text-primary"><i class="fa fa-arrow-left"></i></a></li>
							<li class="nav-item"><a href="#nav-tab-1" data-bs-toggle="tab" class="nav-link active">Summary</a></li>
							<li class="nav-item"><a href="#nav-tab-2" data-bs-toggle="tab" class="nav-link">Transcript</a></li>
							<!--li class="nav-item"><a href="#nav-tab-3" data-bs-toggle="tab" class="nav-link">Nav Tab 3</a></li-->
							<li class="nav-item next-button"><a href="javascript:;" data-click="next-tab" class="nav-link text-primary"><i class="fa fa-arrow-right"></i></a></li>
						</ul>
					</div>
					<!-- END nav-tabs -->
					<div class="panel-heading-btn me-2 ms-2 d-flex">
						<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-secondary" data-toggle="panel-expand"><i class="fa fa-expand"></i></a>
					</div>
				</div>
				<!-- END panel-heading -->
				<!-- BEGIN tab-content -->
				<div class="panel-body tab-content">
					<!-- BEGIN tab-pane -->
					<div class="tab-pane fade active show" id="nav-tab-1">
						<form>
                            {% csrf_token %}
                            <fieldset>
                                <legend><h1 class="mt-10px">{{ video.title }}</h1></legend>
                                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                                {% for summary in video.summary_set.all %}
                                    <label for="summary{{ forloop.counter }}">{{ summary.summary_text | markdownify }}</label><br>
                                {% endfor %}
                            </fieldset>
                        </form>
					</div>
					<!-- END tab-pane -->
					<!-- BEGIN tab-pane -->
					<div class="tab-pane fade" id="nav-tab-2">
                        <p>
                            <h1 class="mt-10px">{{video.title}}</h3>
                                <p>
                                    {{video.transcript}}
                                </p>
                        </p>						
					</div>
					<!-- END tab-pane -->
					<!-- BEGIN tab-pane -->
					<div class="tab-pane fade" id="nav-tab-3">
						<h3 class="mt-10px">Nav Tab 3</h3>
						<p>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
							Integer ac dui eu felis hendrerit lobortis. Phasellus elementum, nibh eget adipiscing porttitor, 
							est diam sagittis orci, a ornare nisi quam elementum tortor. 
							Proin interdum ante porta est convallis dapibus dictum in nibh. 
							Aenean quis massa congue metus mollis fermentum eget et tellus. 
							Aenean tincidunt, mauris ut dignissim lacinia, nisi urna consectetur sapien, 
							nec eleifend orci eros id lectus.
						</p>
						<p>
							Aenean eget odio eu justo mollis consectetur non quis enim. 
							Vivamus interdum quam tortor, et sollicitudin quam pulvinar sit amet. 
							Donec facilisis auctor lorem, quis mollis metus dapibus nec. Donec interdum tellus vel mauris vehicula, 
							at ultrices ex gravida. Maecenas at elit tincidunt, vulputate augue vitae, vulputate neque.
							Aenean vel quam ligula. Etiam faucibus aliquam odio eget condimentum. 
							Cras lobortis, orci nec eleifend ultrices, orci elit pellentesque ex, eu sodales felis urna nec erat. 
							Fusce lacus est, congue quis nisi quis, sodales volutpat lorem.
						</p>
					</div>
					<!-- END tab-pane -->
				</div>
				<!-- END tab-content -->
				<!-- BEGIN hljs-wrapper -->
				<div class="hljs-wrapper">
					<pre><code class="html" data-url="{% static 'data/ui-unlimited-tabs/code-1.json' %}"></code></pre>
				</div>
				<!-- END hljs-wrapper -->
			</div>
			<!-- END panel -->
		</div>
		<!-- END col-9 -->
	</div>
	<!-- END row -->
{% endblock %}

summarizer-web/videos/templates/videos/index.html
{% extends "videos/base.html" %}

{% load static %}

{% block content %}

<h1>Last 5 Videos</h1>


{% if latest_video_list %}
    <table id="data-table-default" width="100%" class="table table-striped table-bordered align-middle text-nowrap">
<thead>
    <tr>
        <th width="1%"></th>
        <th class="text-nowrap">Video URL</th>
        <th class="text-nowrap">Video Title</th>
        <th class="text-nowrap">Channel Name</th>
        <th class="text-nowrap">Duration</th>
        <th class="text-nowrap">Categories</th>
        <th class="text-nowrap">Created At </th>
        <th class="text-nowrap">Updated At </th>
        <th class="text-nowrap">Status</th>
    </tr>
</thead>

<tbody>

    {% for video in latest_video_list %}
    <tr class="odd gradeX">
        <td width="1%" class="fw-bold">{{video.id}}</td>
        <td ><a href="{% url 'detail' video.id %}">{{video.url}}</a></td>
        <td >{{video.title}}</td>
        <td >{{video.channel_name}}</td>
        <td >{{video.duration}}</td>
        <td >{{video.categories}}</td>
        <td >{{video.created_at}}</td>
        <td >{{video.updated_at}}</td>
        <td >{{video.status}}</td>
  </tr>
    {% endfor %}
</tbody>

    </table>
{% else %}
    <p>No videos are available.</p>
{% endif %}
{% endblock %}

summarizer-web/videos/templates/videos/list.html
{% extends 'videos/base.html' %}

{% load static %}

{% block title %}Videos{% endblock %}

{% block css %}
	<link href="{% static 'plugins/datatables.net-bs5/css/dataTables.bootstrap5.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css' %}" rel="stylesheet" />
{% endblock %}

{% block js %}
	<script src="{% static 'plugins/datatables.net/js/dataTables.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-bs5/js/dataTables.bootstrap5.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js' %}"></script>
	<script src="{% static 'js/demo/table-manage-responsive.demo.js' %}"></script>
{% endblock %}

{% block content %}
	<!-- BEGIN breadcrumb -->
	<ol class="breadcrumb float-xl-end">
		<li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
		<li class="breadcrumb-item active">Videos</li>
	</ol>
	<!-- END breadcrumb -->
	<!-- BEGIN page-header -->
	<h1 class="page-header">Videolar <small>tüm videolar...</small></h1>
	<!-- END page-header -->
	<!-- BEGIN row -->
	<div class="row">

		<!-- BEGIN col-12 -->
		<div class="col-xl-12">
			<!-- BEGIN panel -->
			<div class="panel panel-inverse">
				<!-- BEGIN panel-heading -->
				<div class="panel-heading">
					<div class="panel-heading-btn">
						<a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i class="fa fa-expand"></i></a>
						<a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i class="fa fa-redo"></i></a>
						<!--a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i class="fa fa-times"></i></a-->
					</div>
				</div>
				<!-- END panel-heading -->
                <!-- BEGIN panel-body -->
				<div class="panel-body">
					{% if video_list %}
                    <table id="data-table-responsive" width="100%" class="table table-striped table-bordered align-middle text-nowrap">
                        <thead>
                            <tr>
                                <th width="1%"></th>
                                <th class="text-nowrap">Video Title</th>
                                <th class="text-nowrap">Channel Name</th>
                                <th class="text-nowrap">Duration</th>
                                <th class="text-nowrap">Categories</th>
                                <th class="text-nowrap">Created At </th>
                                <th class="text-nowrap">Updated At </th>
                                <th class="text-nowrap">Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for video in video_list %}
                            
                            <tr  class="odd gradeX">
                                <td width="1%" class="fw-bold">{{video.id}}</td>
                                <td ><a href="{% url 'detail' video.id %}">{{video.title}}</a></td>
                                <td >{{video.channel_name}}</td>
                                <td >{{video.duration}}</td>
                                <td >{{video.categories}}</td>
                                <td >{{video.created_at}}</td>
                                <td >{{video.updated_at}}</td>
                                <td >{{video.status}}</td>
                          </tr>
                            {% endfor %}
                        </tbody>
                        
                        
					</table>
                    {% else %}
                    <p>No videos are available.</p>
                    {% endif %}

				</div>
				<!-- END panel-body -->
				<!-- BEGIN hljs-wrapper -->
				<div class="hljs-wrapper">
					<pre><code class="html" data-url="{% static 'data/table-manage/responsive.json' %}"></code></pre>
				</div>
				<!-- END hljs-wrapper -->
			</div>
			<!-- END panel -->
		</div>
		<!-- END col-10 -->
	</div>
	<!-- END row -->
{% endblock %}

summarizer-web/videos/templates/videos/modal.html
<div class="modal fade" id="videoModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Detay</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"><span>&times;</span></button>
            </div>
            <div class="modal-body" id="#modalContent">
                <p><strong>Ad:</strong> {{ video.url }}</p> 
                <p><strong>Açıklama:</strong> {{ video.description }}</p>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-success" data-bs-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>

summarizer-web/videos/templates/videos/modal_warning.html
<div class="modal fade" id="deleteWarningModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Detay</h4>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-hidden="true"><span>&times;</span></button>
            </div>
            <div class="modal-body" id="#modalContent">
                <p> Are you sure you want to delete the <strong> Video:</strong> {{ video.title }}</p> 
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-white" data-bs-dismiss="modal">Close</a>
                <!--a href="javascript:;" class="btn btn-danger">Delete</a-->
            
            	<form action="{% url 'delete_video' video.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">
                        Delete
                    </button>
                </form>
            
            </div>
        </div>
    </div>
</div>

summarizer-web/videos/templates/videos/partial/header.html
{% load static %}
<!-- BEGIN #header -->
<div id="header" class="app-header" data-bs-theme="{% if appHeaderInverse %}dark{% endif %}">
	<!-- BEGIN navbar-header -->
	<div class="navbar-header">
		{% if appSidebarTwo %}
			<button type="button" class="navbar-mobile-toggler" data-toggle="app-sidebar-end-mobile">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
		{% endif %}
		<a href="/" class="navbar-brand"><span class="navbar-logo"></span> <b class="me-3px">Gemini</b> Summarizer</a>
		{% if appHeaderMegaMenu %}
			<button type="button" class="navbar-mobile-toggler collapsed" data-bs-toggle="collapse" data-bs-target="#top-navbar" aria-expanded="false">
				<span class="fa-stack fa-lg">
					<i class="far fa-square fa-stack-2x"></i>
					<i class="fa fa-cog fa-stack-1x"></i>
				</span>
			</button>
		{% endif %}
		<button type="button" class="navbar-mobile-toggler" data-toggle="app-sidebar-mobile">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<!-- END navbar-header -->
	<!-- BEGIN header-nav -->
	<div class="navbar-nav">
		<div class="navbar-item navbar-form">
			<form action="" method="POST" name="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Enter keyword" />
					<button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
				</div>
			</form>
		</div>
	</div>
	<!-- END header-nav -->
</div>
<!-- END #header -->

summarizer-web/videos/templates/videos/partial/scroll-top-btn.html
<!-- BEGIN scroll-top-btn -->
<a href="javascript:;" class="btn btn-icon btn-circle btn-theme btn-scroll-to-top" data-toggle="scroll-to-top"><i class="fa fa-angle-up"></i></a>
<!-- END scroll-top-btn -->

summarizer-web/videos/templates/videos/upload_file.html
{% extends "videos/base.html" %}

{% load static %}

{% block content %}
<!-- upload_file.html -->
<form method="post" action="{% url 'upload_file' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endif %}

{% endblock %}